name: Auto-merge approved dependency PRs

on:
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    name: Merge if all checks pass
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read
      statuses: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./
        with:
          command: merge
          head-sha: ${{ github.event.check_suite.head_sha }}
